import csv
import io
from pathlib import Path

from django.conf import settings
from django.utils import timezone
from django.utils.translation import gettext as _
import openpyxl
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.platypus import (
    HRFlowable,
    Image,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from analytics.selectors import (
    get_deadline_metrics,
    get_department_comparison_data,
    get_executive_metrics,
    get_payroll_analytics_metrics,
    get_scoped_tasks,
    get_signature_metrics,
)


def _get_logo_path():
    dark = settings.BASE_DIR / 'static' / 'images' / 'logo-dark.png'
    light = settings.BASE_DIR / 'static' / 'images' / 'logo-light.png'
    if dark.exists():
        return dark
    if light.exists():
        return light
    return None


def _get_pdf_styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        'ReportHeader',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=16,
        leading=20,
        textColor=colors.HexColor('#1e293b'),
        spaceAfter=4,
    ))
    styles.add(ParagraphStyle(
        'ReportSubHeader',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#64748b'),
        spaceAfter=10,
    ))
    styles.add(ParagraphStyle(
        'SectionHeading',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=16,
        textColor=colors.HexColor('#0f172a'),
        spaceBefore=8,
        spaceAfter=6,
    ))
    styles.add(ParagraphStyle(
        'BodyCell',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=11,
        textColor=colors.HexColor('#334155'),
    ))
    styles.add(ParagraphStyle(
        'HeaderCell',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=9,
        leading=11,
        textColor=colors.HexColor('#ffffff'),
    ))
    return styles


# ===========================================================================
# PDF EXPORT ENGINE
# ===========================================================================

def generate_analytics_pdf(report_title: str, subtitle: str, summary_metrics: dict, table_headers: list[str], table_data: list[list[str]], user_name: str) -> io.BytesIO:
    """
    Generates a university-branded executive analytics PDF report in English.
    """
    from django.utils.translation import override

    with override('en'):
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            leftMargin=36,
            rightMargin=36,
            topMargin=36,
            bottomMargin=36,
        )

        story = []
        styles = _get_pdf_styles()
        now_str = timezone.now().strftime('%Y-%m-%d %H:%M')

        # Header section
        logo_path = _get_logo_path()
        if logo_path and logo_path.exists():
            try:
                from PIL import Image as PILImage
                with PILImage.open(str(logo_path)) as pil_img:
                    orig_w, orig_h = pil_img.size
                aspect = (orig_w / orig_h) if orig_h else 1.0
                target_h = 0.65 * 72
                target_w = target_h * aspect
                logo_img = Image(str(logo_path), width=target_w, height=target_h)
                logo_img.hAlign = 'LEFT'
                story.append(logo_img)
                story.append(Spacer(1, 6))
            except Exception:
                pass

        story.append(Paragraph(f"<b>AL-KHWARIZMI UNIVERSITY</b> — ANALYTICS REPORT", styles['ReportSubHeader']))
        story.append(Paragraph(report_title, styles['ReportHeader']))
        story.append(Paragraph(f"{subtitle} | Generated by: {user_name} ({now_str})", styles['ReportSubHeader']))
        story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#cbd5e1'), spaceBefore=2, spaceAfter=10))

        # Summary metrics grid
        if summary_metrics:
            story.append(Paragraph("Executive Summary Metrics", styles['SectionHeading']))
            summary_rows = []
            items = list(summary_metrics.items())
            for i in range(0, len(items), 2):
                row = []
                k1, v1 = items[i]
                row.extend([Paragraph(f"<b>{k1}:</b>", styles['BodyCell']), Paragraph(str(v1), styles['BodyCell'])])
                if i + 1 < len(items):
                    k2, v2 = items[i + 1]
                    row.extend([Paragraph(f"<b>{k2}:</b>", styles['BodyCell']), Paragraph(str(v2), styles['BodyCell'])])
                else:
                    row.extend(['', ''])
                summary_rows.append(row)

            summary_table = Table(summary_rows, colWidths=[120, 140, 120, 140])
            summary_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#f8fafc')),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
                ('TOPPADDING', (0, 0), (-1, -1), 4),
                ('LEFTPADDING', (0, 0), (-1, -1), 6),
                ('RIGHTPADDING', (0, 0), (-1, -1), 6),
                ('LINEBELOW', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
            ]))
            story.append(summary_table)
            story.append(Spacer(1, 12))

        # Detailed Data Table
        if table_headers and table_data:
            story.append(Paragraph("Detailed Data", styles['SectionHeading']))
            header_row = [Paragraph(f"<b>{h}</b>", styles['HeaderCell']) for h in table_headers]
            data_rows = [[Paragraph(str(cell), styles['BodyCell']) for cell in row] for row in table_data]
            all_rows = [header_row] + data_rows

            col_w = 540 / len(table_headers)
            data_table = Table(all_rows, colWidths=[col_w] * len(table_headers))
            data_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e293b')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('TOPPADDING', (0, 0), (-1, -1), 4),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
                ('LEFTPADDING', (0, 0), (-1, -1), 4),
                ('RIGHTPADDING', (0, 0), (-1, -1), 4),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8fafc')]),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
            ]))
            story.append(data_table)

        # Footer
        story.append(Spacer(1, 14))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#cbd5e1'), spaceBefore=4, spaceAfter=6))
        story.append(Paragraph(
            "Confidential — For authorized university management only. Data generated dynamically from official university databases.",
            ParagraphStyle('Footer', parent=styles['Normal'], fontSize=7.5, textColor=colors.HexColor('#94a3b8'), alignment=1)
        ))

        doc.build(story)
        buffer.seek(0)
        return buffer


# ===========================================================================
# EXCEL EXPORT ENGINE (OpenPyXL)
# ===========================================================================

def generate_analytics_excel(sheet_title: str, summary_metrics: dict, table_headers: list[str], table_data: list[list[str]]) -> io.BytesIO:
    """
    Generates styled Excel (.xlsx) workbook for analytics reporting.
    """
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = sheet_title[:30]

    header_font = Font(name='Segoe UI', size=11, bold=True, color='FFFFFF')
    header_fill = PatternFill(start_color='1E293B', end_color='1E293B', fill_type='solid')
    sub_fill = PatternFill(start_color='F1F5F9', end_color='F1F5F9', fill_type='solid')
    thin_border = Border(
        left=Side(style='thin', color='CBD5E1'),
        right=Side(style='thin', color='CBD5E1'),
        top=Side(style='thin', color='CBD5E1'),
        bottom=Side(style='thin', color='CBD5E1'),
    )

    current_row = 1

    # Title
    ws.cell(row=current_row, column=1, value=f"{_('University Task Management')} - {sheet_title}").font = Font(size=14, bold=True, color='0F172A')
    current_row += 2

    # Summary metrics
    if summary_metrics:
        ws.cell(row=current_row, column=1, value=_("Summary Key Metrics")).font = Font(size=11, bold=True)
        current_row += 1
        for k, v in summary_metrics.items():
            ws.cell(row=current_row, column=1, value=k).font = Font(bold=True)
            ws.cell(row=current_row, column=2, value=str(v))
            current_row += 1
        current_row += 1

    # Detailed table
    if table_headers and table_data:
        for col_idx, h in enumerate(table_headers, 1):
            cell = ws.cell(row=current_row, column=col_idx, value=h)
            cell.font = header_font
            cell.fill = header_fill
            cell.alignment = Alignment(horizontal='center', vertical='center')
        current_row += 1

        for row in table_data:
            for col_idx, val in enumerate(row, 1):
                cell = ws.cell(row=current_row, column=col_idx, value=val)
                cell.border = thin_border
                cell.alignment = Alignment(vertical='center')
            current_row += 1

    # Auto-adjust column widths
    for col in ws.columns:
        max_len = max(len(str(cell.value or '')) for cell in col)
        col_letter = openpyxl.utils.get_column_letter(col[0].column)
        ws.column_dimensions[col_letter].width = max(max_len + 4, 12)

    buffer = io.BytesIO()
    wb.save(buffer)
    buffer.seek(0)
    return buffer


# ===========================================================================
# CSV EXPORT ENGINE
# ===========================================================================

def generate_analytics_csv(table_headers: list[str], table_data: list[list[str]]) -> str:
    """
    Generates standard RFC-4180 CSV string for analytics reporting.
    """
    output = io.StringIO()
    writer = csv.writer(output)
    if table_headers:
        writer.writerow(table_headers)
    for row in table_data:
        writer.writerow(row)
    return output.getvalue()
