# Generated by Django 6.1 on 2026-08-24 18:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL, verbose_name='department head'),
        ),
        migrations.AddField(
            model_name='position',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Leave blank if this position applies university-wide.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='organization.department', verbose_name='department'),
        ),
        migrations.CreateModel(
            name='DepartmentResponsibility',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vice_rector_responsibilities', to='organization.department', verbose_name='department')),
                ('vice_rector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_responsibilities', to=settings.AUTH_USER_MODEL, verbose_name='vice rector')),
            ],
            options={
                'verbose_name': 'department responsibility',
                'verbose_name_plural': 'department responsibilities',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['is_active'], name='organizatio_is_acti_fa5e0e_idx'), models.Index(fields=['vice_rector', 'is_active'], name='organizatio_vice_re_c0fda4_idx'), models.Index(fields=['department', 'is_active'], name='organizatio_departm_bff7ea_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('vice_rector', 'department'), name='unique_active_vice_rector_department_responsibility')],
            },
        ),
    ]
