# Generated by Django 6.1 on 2026-09-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_department_head_position_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='can_supervise',
            field=models.BooleanField(default=False, help_text='Designates whether users in this position can serve as a direct supervisor.', verbose_name='can supervise / management position'),
        ),
    ]
