# Generated by Django 5.1.15 on 2026-09-08 06:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_position_can_supervise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActingRectorDelegation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='reason for delegation')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('acting_rector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acting_rector_delegations', to=settings.AUTH_USER_MODEL, verbose_name='acting rector')),
                ('rector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_granted', to=settings.AUTH_USER_MODEL, verbose_name='rector')),
            ],
            options={
                'verbose_name': 'acting rector delegation',
                'verbose_name_plural': 'acting rector delegations',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['is_active'], name='organizatio_is_acti_1e3762_idx'), models.Index(fields=['acting_rector', 'is_active'], name='organizatio_acting__312233_idx')],
            },
        ),
    ]
