# Generated by Django 6.1 on 2026-08-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_ACTIVATED', 'User Activated'), ('USER_DEACTIVATED', 'User Deactivated'), ('ROLE_CHANGED', 'Role Changed'), ('DEPARTMENT_CREATED', 'Department Created'), ('DEPARTMENT_UPDATED', 'Department Updated'), ('DEPARTMENT_HEAD_ASSIGNED', 'Department Head Assigned'), ('DEPARTMENT_HEAD_CHANGED', 'Department Head Changed'), ('VICE_RECTOR_RESPONSIBILITY_ASSIGNED', 'Vice Rector Responsibility Assigned'), ('VICE_RECTOR_RESPONSIBILITY_REMOVED', 'Vice Rector Responsibility Removed'), ('POSITION_CREATED', 'Position Created'), ('POSITION_UPDATED', 'Position Updated'), ('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('TASK_STATUS_CHANGED', 'Task Status Changed'), ('TASK_CANCELLED', 'Task Cancelled'), ('TASK_ARCHIVED', 'Task Archived'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_UNASSIGNED', 'Task Unassigned'), ('TASK_DEADLINE_CHANGED', 'Task Deadline Changed'), ('TASK_DEPARTMENT_CHANGED', 'Task Department Changed'), ('SUBTASK_CREATED', 'Subtask Created'), ('SUBTASK_UPDATED', 'Subtask Updated'), ('SUBTASK_DELETED', 'Subtask Deleted'), ('DEPENDENCY_CREATED', 'Task Dependency Created'), ('DEPENDENCY_REMOVED', 'Task Dependency Removed'), ('TASK_TYPE_CREATED', 'Task Type Created'), ('TASK_TYPE_UPDATED', 'Task Type Updated')], max_length=64, verbose_name='action'),
        ),
    ]
