# Generated by Django 6.1 on 2026-08-27 16:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_auditlog_action'),
        ('tasks', '0003_alter_taskassignment_assignment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_ACTIVATED', 'User Activated'), ('USER_DEACTIVATED', 'User Deactivated'), ('ROLE_CHANGED', 'Role Changed'), ('DEPARTMENT_CREATED', 'Department Created'), ('DEPARTMENT_UPDATED', 'Department Updated'), ('DEPARTMENT_HEAD_ASSIGNED', 'Department Head Assigned'), ('DEPARTMENT_HEAD_CHANGED', 'Department Head Changed'), ('VICE_RECTOR_RESPONSIBILITY_ASSIGNED', 'Vice Rector Responsibility Assigned'), ('VICE_RECTOR_RESPONSIBILITY_REMOVED', 'Vice Rector Responsibility Removed'), ('POSITION_CREATED', 'Position Created'), ('POSITION_UPDATED', 'Position Updated'), ('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('TASK_STATUS_CHANGED', 'Task Status Changed'), ('TASK_CANCELLED', 'Task Cancelled'), ('TASK_ARCHIVED', 'Task Archived'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_UNASSIGNED', 'Task Unassigned'), ('TASK_DEADLINE_CHANGED', 'Task Deadline Changed'), ('TASK_DEPARTMENT_CHANGED', 'Task Department Changed'), ('SUBTASK_CREATED', 'Subtask Created'), ('SUBTASK_UPDATED', 'Subtask Updated'), ('SUBTASK_DELETED', 'Subtask Deleted'), ('DEPENDENCY_CREATED', 'Task Dependency Created'), ('DEPENDENCY_REMOVED', 'Task Dependency Removed'), ('TASK_TYPE_CREATED', 'Task Type Created'), ('TASK_TYPE_UPDATED', 'Task Type Updated'), ('ASSIGNMENT_ACCEPTED', 'Assignment Accepted'), ('ASSIGNMENT_PROGRESS_UPDATED', 'Assignment Progress Updated'), ('NOTE_CREATED', 'Work Note Created'), ('ASSIGNMENT_SUBMITTED', 'Assignment Submitted for Approval'), ('FIRST_APPROVAL_APPROVED', 'First Approval Granted'), ('FIRST_APPROVAL_REJECTED', 'First Approval Rejected'), ('SECOND_APPROVAL_APPROVED', 'Second Approval Granted'), ('SECOND_APPROVAL_REJECTED', 'Second Approval Rejected'), ('FINAL_APPROVAL', 'Final Approval Granted (Task Completed)'), ('DEADLINE_EXTENDED', 'Task Deadline Extended')], max_length=64, verbose_name='action'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('TASK_ASSIGNED', 'Task Assigned'), ('TASK_SUBMITTED', 'Task Submitted for First Approval'), ('FIRST_APPROVAL_APPROVED', 'First Approval Granted'), ('FIRST_APPROVAL_REJECTED', 'First Approval Rejected'), ('FINAL_APPROVED', 'Task Successfully Completed'), ('FINAL_REJECTED', 'Task Rejected'), ('DEADLINE_EXTENDED', 'Deadline Extended'), ('GENERAL', 'General Notification')], default='GENERAL', max_length=40, verbose_name='notification type')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='link')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='tasks.task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='core_notifi_recipie_aeffaf_idx'), models.Index(fields=['recipient', '-created_at'], name='core_notifi_recipie_4d7e73_idx')],
            },
        ),
    ]
