# Generated by Django 6.1 on 2026-09-04 05:40

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsThresholdConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default Executive Thresholds', max_length=150, verbose_name='configuration name')),
                ('max_acceptable_overdue_tasks', models.PositiveIntegerField(default=5, help_text='Trigger warning when total overdue tasks exceed this threshold.', verbose_name='maximum acceptable overdue tasks')),
                ('min_completion_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('70.00'), help_text='Warning triggered if completion rate falls below this percentage.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='minimum completion rate (%)')),
                ('min_ontime_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('80.00'), help_text='Warning triggered if on-time completion falls below this percentage.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='minimum on-time rate (%)')),
                ('max_rejection_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Warning triggered if task rejection rate exceeds this percentage.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='maximum rejection rate (%)')),
                ('min_kpi_score_percent', models.DecimalField(decimal_places=2, default=Decimal('70.00'), help_text='Warning triggered if average KPI score falls below this threshold.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='minimum acceptable KPI score (%)')),
                ('max_first_approval_wait_days', models.DecimalField(decimal_places=1, default=Decimal('3.0'), help_text='Alert when average first approval queue time exceeds days.', max_digits=4, verbose_name='max first approval wait time (days)')),
                ('max_final_approval_wait_days', models.DecimalField(decimal_places=1, default=Decimal('2.0'), help_text='Alert when average final approval queue time exceeds days.', max_digits=4, verbose_name='max final approval wait time (days)')),
                ('max_signature_wait_days', models.DecimalField(decimal_places=1, default=Decimal('2.0'), help_text='Alert when average electronic signature queue time exceeds days.', max_digits=4, verbose_name='max signature wait time (days)')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Analytics Threshold Configuration',
                'verbose_name_plural': 'Analytics Threshold Configurations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedReportConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='report name')),
                ('report_type', models.CharField(choices=[('UNIVERSITY_TASKS', 'University Task Overview Report'), ('DEPARTMENT_PERFORMANCE', 'Department Performance Report'), ('KPI_SUMMARY', 'KPI & Evaluation Report'), ('PAYROLL_ANALYTICS', 'Payroll & Compensation Analytics Report'), ('SIGNATURE_AUDIT', 'Electronic Signature & Verification Audit Report'), ('DEADLINE_COMPLIANCE', 'Deadline Compliance & Bottleneck Report'), ('HR_DISTRIBUTION', 'HR Workforce & Headcount Distribution Report')], max_length=50, verbose_name='report type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_system_preset', models.BooleanField(default=False, verbose_name='is system preset')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='filter parameters')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_reports', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'Saved Report Configuration',
                'verbose_name_plural': 'Saved Report Configurations',
                'ordering': ['-is_system_preset', 'name'],
            },
        ),
    ]
