# Generated by Django 6.1 on 2026-09-02 16:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeGrade',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('rank', models.IntegerField(default=1, help_text='Lower number means entry level, higher number means executive/senior rank.', verbose_name='rank / level order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'employee grade',
                'verbose_name_plural': 'employee grades',
                'ordering': ['rank', 'code'],
                'indexes': [models.Index(fields=['code'], name='hr_employee_code_3cf10f_idx'), models.Index(fields=['rank'], name='hr_employee_rank_eceda5_idx'), models.Index(fields=['is_active'], name='hr_employee_is_acti_4f5da3_idx')],
            },
        ),
        migrations.CreateModel(
            name='HRPermissionConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_view_employees', models.BooleanField(default=True, verbose_name='can view employees')),
                ('can_create_employees', models.BooleanField(default=False, verbose_name='can create employees')),
                ('can_edit_employees', models.BooleanField(default=True, verbose_name='can edit employees')),
                ('can_deactivate_employees', models.BooleanField(default=False, verbose_name='can deactivate employees')),
                ('can_assign_department', models.BooleanField(default=True, verbose_name='can assign department')),
                ('can_assign_position', models.BooleanField(default=True, verbose_name='can assign position')),
                ('can_assign_grade', models.BooleanField(default=True, verbose_name='can assign grade')),
                ('can_assign_supervisor', models.BooleanField(default=True, verbose_name='can assign supervisor')),
                ('can_manage_departments', models.BooleanField(default=False, verbose_name='can manage departments')),
                ('can_assign_department_head', models.BooleanField(default=False, verbose_name='can assign department head')),
                ('can_assign_vice_rector_responsibility', models.BooleanField(default=False, verbose_name='can assign vice rector responsibility')),
                ('can_view_kpi', models.BooleanField(default=True, verbose_name='can view KPI')),
                ('can_manage_kpi', models.BooleanField(default=False, verbose_name='can manage KPI definitions & assignments')),
                ('can_approve_kpi', models.BooleanField(default=False, verbose_name='can approve KPI results')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_authority', to=settings.AUTH_USER_MODEL, verbose_name='authorized user')),
            ],
            options={
                'verbose_name': 'HR authority configuration',
                'verbose_name_plural': 'HR authority configurations',
            },
        ),
    ]
