# Generated by Django 6.1 on 2026-09-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrpermissionconfig',
            name='can_approve_payroll',
            field=models.BooleanField(default=False, verbose_name='can approve payroll records'),
        ),
        migrations.AddField(
            model_name='hrpermissionconfig',
            name='can_create_adjustment',
            field=models.BooleanField(default=False, verbose_name='can create payroll adjustments'),
        ),
        migrations.AddField(
            model_name='hrpermissionconfig',
            name='can_manage_payroll',
            field=models.BooleanField(default=False, verbose_name='can manage payroll periods & calculation'),
        ),
        migrations.AddField(
            model_name='hrpermissionconfig',
            name='can_manage_salary',
            field=models.BooleanField(default=False, verbose_name='can manage employee salaries'),
        ),
        migrations.AddField(
            model_name='hrpermissionconfig',
            name='can_mark_paid',
            field=models.BooleanField(default=False, verbose_name='can mark payroll as paid'),
        ),
        migrations.AddField(
            model_name='hrpermissionconfig',
            name='can_view_payroll',
            field=models.BooleanField(default=False, verbose_name='can view payroll'),
        ),
        migrations.AddField(
            model_name='hrpermissionconfig',
            name='can_view_payroll_reports',
            field=models.BooleanField(default=False, verbose_name='can view payroll reports'),
        ),
    ]
