# Generated by Django 6.1 on 2026-09-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('RECTOR', 'Rector'), ('VICE_RECTOR', 'Vice Rector'), ('DEPARTMENT_HEAD', 'Department Head'), ('EMPLOYEE', 'Employee')], max_length=50, unique=True, verbose_name='code'),
        ),
    ]
