# Generated by Django 6.1 on 2026-09-02 16:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_role_code'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hr', '__first__'),
        ('organization', '0002_department_head_position_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employment_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='employment end date'),
        ),
        migrations.AddField(
            model_name='user',
            name='employment_start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='employment start date'),
        ),
        migrations.AddField(
            model_name='user',
            name='employment_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ON_LEAVE', 'On Leave'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20, verbose_name='employment status'),
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='hr.employeegrade', verbose_name='grade / level'),
        ),
        migrations.AddField(
            model_name='user',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL, verbose_name='supervisor'),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('RECTOR', 'Rector'), ('VICE_RECTOR', 'Vice Rector'), ('DEPARTMENT_HEAD', 'Department Head'), ('HR', 'HR Manager'), ('EMPLOYEE', 'Employee')], max_length=50, unique=True, verbose_name='code'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['employment_status'], name='accounts_us_employm_fa337b_idx'),
        ),
    ]
