# Generated by Django 5.1.15 on 2026-09-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_employment_end_date_user_employment_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('RECTOR', 'Rector'), ('VICE_RECTOR', 'Vice Rector'), ('DEPARTMENT_HEAD', 'Department Head'), ('HR', 'HR Manager'), ('FINANCE', 'Finance / Accountant'), ('EMPLOYEE', 'Employee')], max_length=50, unique=True, verbose_name='code'),
        ),
    ]
