# Generated by Django 5.1.15 on 2026-09-07 03:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_role_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cv_file',
            field=models.FileField(blank=True, help_text='Only PDF files are allowed.', null=True, upload_to='cvs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='CV / Resume (PDF)'),
        ),
        migrations.AddField(
            model_name='user',
            name='leave_notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='leave / permission details'),
        ),
        migrations.AddField(
            model_name='user',
            name='leave_status',
            field=models.CharField(choices=[('NONE', 'None / Active Duty'), ('PERMISSION', 'Excused Absence / Permission'), ('VACATION', 'Vacation / Annual Leave'), ('SICK_LEAVE', 'Sick Leave'), ('BUSINESS_TRIP', 'Business Trip'), ('UNPAID_LEAVE', 'Unpaid Leave')], default='NONE', max_length=20, verbose_name='leave / permission status'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_presence',
            field=models.CharField(choices=[('PRESENT', 'At Work / Present'), ('REMOTE', 'Working Remotely'), ('ABSENT', 'Absent / Not at Work')], default='PRESENT', max_length=20, verbose_name='work presence'),
        ),
    ]
