# Generated by Django 6.1 on 2026-09-04 07:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='integration name')),
                ('service_type', models.CharField(choices=[('HEMIS_SIS', 'HEMIS Higher Education Management System'), ('MOODLE_LMS', 'Moodle LMS Platform'), ('HR_REGISTRY', 'National Ministry HR Registry'), ('UZASBO_FINANCE', 'UzASBO / University Treasury'), ('CUSTOM_WEBHOOK', 'Custom Enterprise Webhook')], max_length=40, verbose_name='service type')),
                ('api_endpoint', models.URLField(max_length=500, verbose_name='API base endpoint URL')),
                ('auth_header_name', models.CharField(default='Authorization', max_length=100, verbose_name='auth header name')),
                ('auth_token', models.CharField(blank=True, max_length=500, verbose_name='API authentication token / secret')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('config_payload', models.JSONField(blank=True, default=dict, help_text='JSON parameters, webhook secrets, retry policies, or sync filters.', verbose_name='custom configuration')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='last synchronized at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'external integration',
                'verbose_name_plural': 'external integrations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_type', models.CharField(default='SYNC_ROUTINE', max_length=80, verbose_name='sync operation type')),
                ('records_processed', models.PositiveIntegerField(default=0, verbose_name='records processed count')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial Success')], max_length=20, verbose_name='execution status')),
                ('response_code', models.IntegerField(blank=True, null=True, verbose_name='HTTP response status code')),
                ('error_details', models.TextField(blank=True, verbose_name='error message or trace details')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='executed at')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='communication.externalintegration', verbose_name='integration')),
            ],
            options={
                'verbose_name': 'integration sync log',
                'verbose_name_plural': 'integration sync logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enable_in_app', models.BooleanField(default=True, verbose_name='enable in-app notifications')),
                ('enable_email', models.BooleanField(default=True, verbose_name='enable email notifications')),
                ('enable_telegram', models.BooleanField(default=True, verbose_name='enable telegram notifications')),
                ('enable_push', models.BooleanField(default=True, verbose_name='enable web push notifications')),
                ('notify_task_assignments', models.BooleanField(default=True, verbose_name='task assignments')),
                ('notify_workflow_approvals', models.BooleanField(default=True, verbose_name='workflow & approval requests')),
                ('notify_deadline_reminders', models.BooleanField(default=True, verbose_name='deadline reminders & escalations')),
                ('notify_system_security', models.BooleanField(default=True, verbose_name='security & system updates')),
                ('notify_payroll_updates', models.BooleanField(default=True, verbose_name='personal payroll & compensation updates')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'notification preference',
                'verbose_name_plural': 'notification preferences',
            },
        ),
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_chat_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='telegram chat ID')),
                ('telegram_username', models.CharField(blank=True, max_length=100, verbose_name='telegram username')),
                ('verification_token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='verification token')),
                ('is_verified', models.BooleanField(default=False, verbose_name='is connected and verified')),
                ('connected_at', models.DateTimeField(blank=True, null=True, verbose_name='connected at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'telegram profile',
                'verbose_name_plural': 'telegram profiles',
            },
        ),
        migrations.CreateModel(
            name='UserCalendarFeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret_token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='calendar feed secret token')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('include_deadlines', models.BooleanField(default=True, verbose_name='include task deadlines')),
                ('include_approvals', models.BooleanField(default=True, verbose_name='include pending approval milestones')),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='last synced by external calendar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_feed', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'calendar feed',
                'verbose_name_plural': 'calendar feeds',
            },
        ),
        migrations.CreateModel(
            name='WebPushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.TextField(unique=True, verbose_name='push endpoint')),
                ('p256dh_key', models.CharField(max_length=255, verbose_name='P256DH key')),
                ('auth_key', models.CharField(max_length=255, verbose_name='auth key')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='client user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'web push subscription',
                'verbose_name_plural': 'web push subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
