# Generated by Django 6.1 on 2026-09-04 07:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0003_position_can_supervise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Discussion', max_length=200, verbose_name='conversation topic')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'AI conversation',
                'verbose_name_plural': 'AI conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'AI Assistant'), ('SYSTEM', 'System Prompt')], max_length=20, verbose_name='message role')),
                ('content', models.TextField(verbose_name='content text / markdown')),
                ('intent_detected', models.CharField(blank=True, max_length=80, verbose_name='detected intent')),
                ('context_snapshot', models.JSONField(blank=True, default=dict, help_text='Redacted, authorization-scoped database snapshot used to ground this response.', verbose_name='role-scoped context snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.aiconversation', verbose_name='conversation')),
            ],
            options={
                'verbose_name': 'AI message',
                'verbose_name_plural': 'AI messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutiveBriefing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='briefing title')),
                ('period_start', models.DateField(verbose_name='period start date')),
                ('period_end', models.DateField(verbose_name='period end date')),
                ('summary_markdown', models.TextField(verbose_name='executive briefing text (markdown)')),
                ('kpis_snapshot', models.JSONField(blank=True, default=dict, verbose_name='KPI metrics snapshot payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='generated at')),
                ('generated_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_briefings', to=settings.AUTH_USER_MODEL, verbose_name='generated for leader')),
            ],
            options={
                'verbose_name': 'executive briefing',
                'verbose_name_plural': 'executive briefings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagementRiskIndicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_type', models.CharField(choices=[('DEADLINE_SPIKE', 'Impending Overdue Deadline Spike'), ('APPROVAL_BOTTLENECK', 'Stage 1 / Stage 2 Approval Bottleneck'), ('WORKLOAD_IMBALANCE', 'Staff Workload Overload / Imbalance'), ('SLA_VIOLATION_TREND', 'Elevated SLA Violation Trend'), ('LOW_COMPLETION_RATE', 'Low Department Task Velocity')], max_length=40, verbose_name='risk category')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20, verbose_name='severity level')),
                ('title', models.CharField(max_length=255, verbose_name='risk summary title')),
                ('description', models.TextField(verbose_name='detailed diagnosis and suggested remedy')),
                ('target_object_repr', models.CharField(blank=True, max_length=200, verbose_name='target entity representation')),
                ('metrics_payload', models.JSONField(blank=True, default=dict, verbose_name='diagnostic metrics payload')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='is resolved')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='detected at')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_indicators', to='organization.department', verbose_name='affected department')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_risks', to=settings.AUTH_USER_MODEL, verbose_name='resolved by user')),
            ],
            options={
                'verbose_name': 'management risk indicator',
                'verbose_name_plural': 'management risk indicators',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['is_resolved', 'severity'], name='ai_assistan_is_reso_71b30e_idx'), models.Index(fields=['department', 'is_resolved'], name='ai_assistan_departm_72b2fb_idx')],
            },
        ),
    ]
