# Generated by Django 6.1 on 2026-08-25 16:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_department_head_position_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE SEQUENCE IF NOT EXISTS task_number_seq START 1;",
            reverse_sql="DROP SEQUENCE IF EXISTS task_number_seq;",
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'task type',
                'verbose_name_plural': 'task types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_number', models.CharField(blank=True, db_index=True, max_length=20, unique=True, verbose_name='task number')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='MEDIUM', max_length=10, verbose_name='priority')),
                ('complexity', models.CharField(choices=[('SIMPLE', 'Simple'), ('MEDIUM', 'Medium'), ('COMPLEX', 'Complex'), ('CRITICAL', 'Critical')], db_index=True, default='SIMPLE', max_length=10, verbose_name='complexity')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=30, verbose_name='status')),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='progress (%)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('deadline', models.DateField(blank=True, db_index=True, null=True, verbose_name='deadline')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='cancellation reason')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archived at')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_tasks', to=settings.AUTH_USER_MODEL, verbose_name='cancelled by')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('responsible_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='organization.department', verbose_name='responsible department')),
                ('task_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.tasktype', verbose_name='task type')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='TODO', max_length=20, verbose_name='status')),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='progress (%)')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='deadline')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtask_assignments', to=settings.AUTH_USER_MODEL, verbose_name='assignee')),
                ('parent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task', verbose_name='parent task')),
            ],
            options={
                'verbose_name': 'subtask',
                'verbose_name_plural': 'subtasks',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('default_priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10, verbose_name='default priority')),
                ('default_complexity', models.CharField(choices=[('SIMPLE', 'Simple'), ('MEDIUM', 'Medium'), ('COMPLEX', 'Complex'), ('CRITICAL', 'Critical')], default='SIMPLE', max_length=10, verbose_name='default complexity')),
                ('default_duration_days', models.PositiveIntegerField(blank=True, help_text='Number of days from creation to deadline.', null=True, verbose_name='default duration (days)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_templates', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('task_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='tasks.tasktype', verbose_name='task type')),
            ],
            options={
                'verbose_name': 'task template',
                'verbose_name_plural': 'task templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecurringTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=10, verbose_name='frequency')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('next_run_at', models.DateField(blank=True, null=True, verbose_name='next run at')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_tasks', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('responsible_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_tasks', to='organization.department', verbose_name='responsible department')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_tasks', to='tasks.tasktemplate', verbose_name='template')),
            ],
            options={
                'verbose_name': 'recurring task',
                'verbose_name_plural': 'recurring tasks',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='assigned at')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary assignee')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='assigned by')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tasks.task', verbose_name='task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to=settings.AUTH_USER_MODEL, verbose_name='assigned user')),
            ],
            options={
                'verbose_name': 'task assignment',
                'verbose_name_plural': 'task assignments',
                'ordering': ['-is_primary', 'assigned_at'],
                'indexes': [models.Index(fields=['task', 'user'], name='tasks_taska_task_id_bf9d8a_idx'), models.Index(fields=['user'], name='tasks_taska_user_id_d33430_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('task',), name='unique_primary_assignment_per_task'), models.UniqueConstraint(fields=('task', 'user'), name='unique_task_user_assignment')],
            },
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dependency_type', models.CharField(choices=[('FINISH_TO_START', 'Finish to Start'), ('START_TO_START', 'Start to Start'), ('FINISH_TO_FINISH', 'Finish to Finish'), ('START_TO_FINISH', 'Start to Finish')], default='FINISH_TO_START', max_length=20, verbose_name='dependency type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='tasks.task', verbose_name='depends on')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='tasks.task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'task dependency',
                'verbose_name_plural': 'task dependencies',
                'constraints': [models.UniqueConstraint(fields=('task', 'depends_on'), name='unique_task_dependency')],
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('STATUS_CHANGED', 'Status Changed'), ('PRIORITY_CHANGED', 'Priority Changed'), ('COMPLEXITY_CHANGED', 'Complexity Changed'), ('DEADLINE_CHANGED', 'Deadline Changed'), ('DEPARTMENT_CHANGED', 'Department Changed'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_UNASSIGNED', 'User Unassigned'), ('TASK_CANCELLED', 'Task Cancelled'), ('TASK_ARCHIVED', 'Task Archived'), ('SUBTASK_CREATED', 'Subtask Created'), ('DEPENDENCY_ADDED', 'Dependency Added'), ('DEPENDENCY_REMOVED', 'Dependency Removed'), ('PROGRESS_UPDATED', 'Progress Updated')], max_length=30, verbose_name='event type')),
                ('old_value', models.JSONField(blank=True, default=dict, verbose_name='old value')),
                ('new_value', models.JSONField(blank=True, default=dict, verbose_name='new value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_history_entries', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tasks.task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'task history',
                'verbose_name_plural': 'task history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', 'created_at'], name='tasks_taskh_task_id_a299e9_idx'), models.Index(fields=['event_type'], name='tasks_taskh_event_t_612d7f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='tasks_task_status_4a0a95_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='tasks_task_priorit_a900d4_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['complexity'], name='tasks_task_complex_9228a8_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['deadline'], name='tasks_task_deadlin_736196_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['creator'], name='tasks_task_creator_b6157f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['responsible_department', 'status'], name='tasks_task_respons_6f6876_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'deadline'], name='tasks_task_status_e8ffa7_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['creator', 'status'], name='tasks_task_creator_914dac_idx'),
        ),
    ]
