# Generated by Django 6.1 on 2026-08-27 15:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='content')),
            ],
            options={
                'verbose_name': 'task note',
                'verbose_name_plural': 'task notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_text', models.TextField(verbose_name='submission text')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='submitted at')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('status', models.CharField(choices=[('PENDING_FIRST_APPROVAL', 'Pending First Approval'), ('FIRST_APPROVED', 'First Approved'), ('FIRST_REJECTED', 'First Rejected'), ('FINAL_APPROVED', 'Final Approved'), ('FINAL_REJECTED', 'Final Rejected')], default='PENDING_FIRST_APPROVAL', max_length=30, verbose_name='status')),
            ],
            options={
                'verbose_name': 'task submission',
                'verbose_name_plural': 'task submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='accepted at'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='assignment_status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted for Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='ASSIGNED', max_length=20, verbose_name='assignment status'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='assignment progress (%)'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='event_type',
            field=models.CharField(choices=[('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('STATUS_CHANGED', 'Status Changed'), ('PRIORITY_CHANGED', 'Priority Changed'), ('COMPLEXITY_CHANGED', 'Complexity Changed'), ('DEADLINE_CHANGED', 'Deadline Changed'), ('DEPARTMENT_CHANGED', 'Department Changed'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_UNASSIGNED', 'User Unassigned'), ('TASK_CANCELLED', 'Task Cancelled'), ('TASK_ARCHIVED', 'Task Archived'), ('SUBTASK_CREATED', 'Subtask Created'), ('DEPENDENCY_ADDED', 'Dependency Added'), ('DEPENDENCY_REMOVED', 'Dependency Removed'), ('PROGRESS_UPDATED', 'Progress Updated'), ('TASK_ACCEPTED', 'Task Accepted'), ('ASSIGNMENT_PROGRESS_UPDATED', 'Assignment Progress Updated'), ('TASK_NOTE_CREATED', 'Work Note Added'), ('TASK_SUBMISSION_CREATED', 'Submitted for First Approval')], max_length=30, verbose_name='event type'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['assignment_status'], name='tasks_taska_assignm_2277cf_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['user', 'assignment_status'], name='tasks_taska_user_id_a13a14_idx'),
        ),
        migrations.AddField(
            model_name='tasknote',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tasks.taskassignment', verbose_name='assignment'),
        ),
        migrations.AddField(
            model_name='tasknote',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_notes', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='tasknote',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tasks.task', verbose_name='task'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tasks.taskassignment', verbose_name='assignment'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_submissions', to=settings.AUTH_USER_MODEL, verbose_name='submitted by'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tasks.task', verbose_name='task'),
        ),
        migrations.AddIndex(
            model_name='tasknote',
            index=models.Index(fields=['task', 'created_at'], name='tasks_taskn_task_id_64bd75_idx'),
        ),
        migrations.AddIndex(
            model_name='tasknote',
            index=models.Index(fields=['assignment'], name='tasks_taskn_assignm_e0ba30_idx'),
        ),
        migrations.AddIndex(
            model_name='tasknote',
            index=models.Index(fields=['author'], name='tasks_taskn_author__b32f25_idx'),
        ),
        migrations.AddIndex(
            model_name='tasksubmission',
            index=models.Index(fields=['task', 'submitted_at'], name='tasks_tasks_task_id_ef6450_idx'),
        ),
        migrations.AddIndex(
            model_name='tasksubmission',
            index=models.Index(fields=['assignment', 'version'], name='tasks_tasks_assignm_e17954_idx'),
        ),
        migrations.AddIndex(
            model_name='tasksubmission',
            index=models.Index(fields=['status'], name='tasks_tasks_status_9cce21_idx'),
        ),
        migrations.AddConstraint(
            model_name='tasksubmission',
            constraint=models.UniqueConstraint(fields=('assignment', 'version'), name='unique_submission_version_per_assignment'),
        ),
    ]
