# Generated by Django 6.1 on 2026-08-27 16:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_phase4_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignment',
            name='assignment_status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted for Approval'), ('SECOND_APPROVAL', 'Pending Second Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='ASSIGNED', max_length=20, verbose_name='assignment status'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='event_type',
            field=models.CharField(choices=[('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('STATUS_CHANGED', 'Status Changed'), ('PRIORITY_CHANGED', 'Priority Changed'), ('COMPLEXITY_CHANGED', 'Complexity Changed'), ('DEADLINE_CHANGED', 'Deadline Changed'), ('DEPARTMENT_CHANGED', 'Department Changed'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_UNASSIGNED', 'User Unassigned'), ('TASK_CANCELLED', 'Task Cancelled'), ('TASK_ARCHIVED', 'Task Archived'), ('SUBTASK_CREATED', 'Subtask Created'), ('DEPENDENCY_ADDED', 'Dependency Added'), ('DEPENDENCY_REMOVED', 'Dependency Removed'), ('PROGRESS_UPDATED', 'Progress Updated'), ('TASK_ACCEPTED', 'Task Accepted'), ('ASSIGNMENT_PROGRESS_UPDATED', 'Assignment Progress Updated'), ('TASK_NOTE_CREATED', 'Work Note Added'), ('TASK_SUBMISSION_CREATED', 'Submitted for First Approval'), ('FIRST_APPROVAL_APPROVED', 'First Approval Granted'), ('FIRST_APPROVAL_REJECTED', 'First Approval Rejected'), ('SECOND_APPROVAL_APPROVED', 'Second Approval Granted'), ('SECOND_APPROVAL_REJECTED', 'Second Approval Rejected'), ('FINAL_APPROVAL', 'Final Approval Granted (Task Completed)'), ('DEADLINE_EXTENDED', 'Task Deadline Extended')], max_length=30, verbose_name='event type'),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='status',
            field=models.CharField(choices=[('PENDING_FIRST_APPROVAL', 'Pending First Approval'), ('FIRST_APPROVED', 'First Approved (Pending Second Approval)'), ('FIRST_REJECTED', 'First Rejected'), ('FINAL_APPROVED', 'Final Approved'), ('FINAL_REJECTED', 'Final Rejected')], default='PENDING_FIRST_APPROVAL', max_length=30, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='TaskApproval',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('FIRST_APPROVAL', 'First Approval (Department Head)'), ('SECOND_APPROVAL', 'Second Approval (Management)'), ('FINAL_APPROVAL', 'Final Approval')], max_length=30, verbose_name='stage')),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20, verbose_name='decision')),
                ('actor_role_code', models.CharField(blank=True, max_length=50, verbose_name='actor role code')),
                ('reason', models.TextField(blank=True, verbose_name='reason / comments')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_approvals_given', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='tasks.taskassignment', verbose_name='assignment')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='tasks.tasksubmission', verbose_name='submission')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='tasks.task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'task approval record',
                'verbose_name_plural': 'task approval records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', '-created_at'], name='tasks_taska_task_id_ede7b1_idx'), models.Index(fields=['assignment', 'stage'], name='tasks_taska_assignm_926025_idx'), models.Index(fields=['decision'], name='tasks_taska_decisio_143370_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskDeadlineExtension',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_deadline', models.DateField(verbose_name='old deadline')),
                ('new_deadline', models.DateField(verbose_name='new deadline')),
                ('reason', models.TextField(verbose_name='reason')),
                ('extended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deadline_extensions_granted', to=settings.AUTH_USER_MODEL, verbose_name='extended by')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_extensions', to='tasks.task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'deadline extension',
                'verbose_name_plural': 'deadline extensions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', '-created_at'], name='tasks_taskd_task_id_a1b722_idx')],
            },
        ),
    ]
