# Generated by Django 6.1 on 2026-08-28 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_taskassignment_assignment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tasknote',
            name='visibility',
            field=models.CharField(choices=[('EMPLOYEE', 'All (Assignees & Management)'), ('DEPARTMENT_HEAD', 'Department Head & Management'), ('MANAGEMENT', 'Management Only (Rector / Vice Rector)'), ('INTERNAL', 'Internal (Author Only)')], db_index=True, default='EMPLOYEE', max_length=20, verbose_name='visibility'),
        ),
        migrations.AddIndex(
            model_name='tasknote',
            index=models.Index(fields=['visibility'], name='tasks_taskn_visibil_c92d90_idx'),
        ),
    ]
