# Generated by Django 5.1.15 on 2026-09-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_actingrectordelegation'),
        ('tasks', '0004_tasknote_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='secondary_departments',
            field=models.ManyToManyField(blank=True, related_name='co_responsible_tasks', to='organization.department', verbose_name='co-responsible / secondary departments'),
        ),
    ]
