# Generated by Django 5.1.15 on 2026-09-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_secondary_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='event_type',
            field=models.CharField(choices=[('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('STATUS_CHANGED', 'Status Changed'), ('PRIORITY_CHANGED', 'Priority Changed'), ('COMPLEXITY_CHANGED', 'Complexity Changed'), ('DEADLINE_CHANGED', 'Deadline Changed'), ('DEPARTMENT_CHANGED', 'Department Changed'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_UNASSIGNED', 'User Unassigned'), ('TASK_CANCELLED', 'Task Cancelled'), ('TASK_ARCHIVED', 'Task Archived'), ('SUBTASK_CREATED', 'Subtask Created'), ('DEPENDENCY_ADDED', 'Dependency Added'), ('DEPENDENCY_REMOVED', 'Dependency Removed'), ('PROGRESS_UPDATED', 'Progress Updated'), ('TASK_ACCEPTED', 'Task Accepted'), ('ASSIGNMENT_PROGRESS_UPDATED', 'Assignment Progress Updated'), ('TASK_NOTE_CREATED', 'Work Note Added'), ('TASK_SUBMISSION_CREATED', 'Submitted for First Approval'), ('TASK_REWORK_STARTED', 'Task Rework Started'), ('FIRST_APPROVAL_APPROVED', 'First Approval Granted'), ('FIRST_APPROVAL_REJECTED', 'First Approval Rejected'), ('SECOND_APPROVAL_APPROVED', 'Second Approval Granted'), ('SECOND_APPROVAL_REJECTED', 'Second Approval Rejected'), ('FINAL_APPROVAL', 'Final Approval Granted (Task Completed)'), ('DEADLINE_EXTENDED', 'Task Deadline Extended')], max_length=30, verbose_name='event type'),
        ),
    ]
