# Generated by Django 6.1 on 2026-09-03 04:00

import django.db.models.deletion
import payroll.validators
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0002_hrpermissionconfig_can_approve_payroll_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIPayrollRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='rule name')),
                ('min_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[payroll.validators.validate_percentage], verbose_name='minimum score threshold (inclusive)')),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[payroll.validators.validate_percentage], verbose_name='maximum score threshold (inclusive)')),
                ('bonus_type', models.CharField(choices=[('PERCENTAGE', 'Percentage of Base Salary'), ('FIXED', 'Fixed Monetary Amount')], default='PERCENTAGE', max_length=20, verbose_name='bonus type')),
                ('bonus_value', models.DecimalField(decimal_places=2, max_digits=18, validators=[payroll.validators.validate_non_negative_decimal], verbose_name='bonus value (% or fixed amount)')),
                ('effective_from', models.DateField(verbose_name='effective from')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='effective to')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'KPI payroll bonus rule',
                'verbose_name_plural': 'KPI payroll bonus rules',
                'ordering': ['min_score'],
            },
        ),
        migrations.CreateModel(
            name='PayrollTaxRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='tax rule name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='tax code')),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[payroll.validators.validate_percentage], verbose_name='tax rate (%)')),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[payroll.validators.validate_non_negative_decimal], verbose_name='fixed tax deduction amount')),
                ('applies_to', models.CharField(choices=[('GROSS', 'Gross Salary'), ('TAXABLE_GROSS', 'Taxable Gross (Taxable Allowances + Base)'), ('BASE_SALARY', 'Base Salary Only')], default='TAXABLE_GROSS', max_length=25, verbose_name='applies to base')),
                ('effective_from', models.DateField(verbose_name='effective from date')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='effective to date')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'payroll tax rule',
                'verbose_name_plural': 'payroll tax rules',
                'ordering': ['-effective_from', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompensationComponent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='component name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='component code')),
                ('component_type', models.CharField(choices=[('ALLOWANCE', 'Allowance'), ('BONUS', 'Bonus'), ('DEDUCTION', 'Deduction')], default='ALLOWANCE', max_length=20, verbose_name='component type')),
                ('calculation_type', models.CharField(choices=[('FIXED', 'Fixed Monetary Amount'), ('PERCENTAGE', 'Percentage of Base Salary')], default='FIXED', max_length=20, verbose_name='calculation type')),
                ('default_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[payroll.validators.validate_non_negative_decimal], verbose_name='default rate / value')),
                ('is_taxable', models.BooleanField(default=True, verbose_name='is subject to tax')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('description', models.TextField(blank=True, verbose_name='description / purpose')),
            ],
            options={
                'verbose_name': 'compensation component',
                'verbose_name_plural': 'compensation components',
                'ordering': ['component_type', 'name'],
                'indexes': [models.Index(fields=['code'], name='payroll_com_code_96f115_idx'), models.Index(fields=['component_type', 'is_active'], name='payroll_com_compone_3f8773_idx')],
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='period name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='period code')),
                ('period_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20, verbose_name='period type')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open / In Progress'), ('CALCULATING', 'Calculating'), ('PENDING_APPROVAL', 'Pending Final Approval'), ('APPROVED', 'Approved & Locked'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=25, verbose_name='status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_periods', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_payroll_periods', to=settings.AUTH_USER_MODEL, verbose_name='closed by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_periods', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'payroll period',
                'verbose_name_plural': 'payroll periods',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_name_snapshot', models.CharField(max_length=255, verbose_name='employee full name at calculation')),
                ('employee_username_snapshot', models.CharField(max_length=150, verbose_name='employee username at calculation')),
                ('department_snapshot', models.CharField(blank=True, max_length=255, verbose_name='department at calculation')),
                ('position_snapshot', models.CharField(blank=True, max_length=255, verbose_name='position at calculation')),
                ('grade_snapshot', models.CharField(blank=True, max_length=100, verbose_name='grade at calculation')),
                ('kpi_score_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='approved KPI score at calculation')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=18, validators=[payroll.validators.validate_non_negative_decimal], verbose_name='base salary')),
                ('total_allowances', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='total allowances')),
                ('total_bonuses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='total standard bonuses')),
                ('kpi_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='performance / KPI bonus')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='total non-tax deductions')),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='gross salary')),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='total tax deducted')),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='net salary payable')),
                ('currency', models.CharField(default='UZS', max_length=10, verbose_name='currency')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CALCULATED', 'Calculated'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved & Locked'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=25, verbose_name='status')),
                ('calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='calculated at')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('notes', models.TextField(blank=True, verbose_name='calculation notes / remarks')),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('READY', 'Ready for Disbursement'), ('PAID', 'Paid')], default='UNPAID', max_length=20, verbose_name='payment status')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='disbursed at')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='payment document / transaction reference')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_records', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_records', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursed_payroll_records', to=settings.AUTH_USER_MODEL, verbose_name='paid by / disbursed by')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='payroll.payrollperiod', verbose_name='payroll period')),
            ],
            options={
                'verbose_name': 'payroll record',
                'verbose_name_plural': 'payroll records',
                'ordering': ['-period__start_date', 'employee_name_snapshot'],
            },
        ),
        migrations.CreateModel(
            name='PayrollLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_snapshot', models.CharField(max_length=150, verbose_name='item description snapshot')),
                ('component_type', models.CharField(choices=[('ALLOWANCE', 'Allowance'), ('BONUS', 'Bonus'), ('DEDUCTION', 'Deduction')], max_length=20, verbose_name='component type')),
                ('calculation_type', models.CharField(choices=[('FIXED', 'Fixed Monetary Amount'), ('PERCENTAGE', 'Percentage of Base Salary')], max_length=20, verbose_name='calculation type')),
                ('rate_or_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='rate / base value')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='calculated line amount')),
                ('taxable', models.BooleanField(default=True, verbose_name='is taxable')),
                ('description', models.TextField(blank=True, verbose_name='line details / memo')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_lines', to='payroll.compensationcomponent', verbose_name='component source')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.payrollrecord', verbose_name='payroll record')),
            ],
            options={
                'verbose_name': 'payroll line item',
                'verbose_name_plural': 'payroll line items',
                'ordering': ['component_type', 'name_snapshot'],
            },
        ),
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('BONUS', 'Discretionary Bonus'), ('ALLOWANCE', 'Special Allowance'), ('DEDUCTION', 'Penalty / Deduction'), ('CORRECTION', 'Calculation Correction')], max_length=20, verbose_name='adjustment type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='adjustment amount')),
                ('reason', models.TextField(verbose_name='mandatory reason')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='payroll.payrollperiod', verbose_name='payroll period')),
                ('payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='payroll.payrollrecord', verbose_name='associated payroll record')),
            ],
            options={
                'verbose_name': 'payroll adjustment',
                'verbose_name_plural': 'payroll adjustments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryBand',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=18, validators=[payroll.validators.validate_positive_decimal], verbose_name='minimum salary')),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=18, validators=[payroll.validators.validate_positive_decimal], verbose_name='maximum salary')),
                ('currency', models.CharField(default='UZS', max_length=10, verbose_name='currency')),
                ('effective_from', models.DateField(verbose_name='effective from')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='effective to')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_bands', to='hr.employeegrade', verbose_name='employee grade')),
            ],
            options={
                'verbose_name': 'salary band',
                'verbose_name_plural': 'salary bands',
                'ordering': ['grade__rank', 'min_salary'],
            },
        ),
        migrations.CreateModel(
            name='SalaryHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='previous salary')),
                ('new_salary', models.DecimalField(decimal_places=2, max_digits=18, validators=[payroll.validators.validate_positive_decimal], verbose_name='new salary')),
                ('currency', models.CharField(default='UZS', max_length=10, verbose_name='currency')),
                ('effective_from', models.DateField(verbose_name='effective from date')),
                ('reason', models.TextField(verbose_name='reason for adjustment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_salary_changes', to=settings.AUTH_USER_MODEL, verbose_name='changed by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_histories', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
            ],
            options={
                'verbose_name': 'salary history record',
                'verbose_name_plural': 'salary history records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=18, validators=[payroll.validators.validate_positive_decimal], verbose_name='base salary amount')),
                ('currency', models.CharField(default='UZS', max_length=10, verbose_name='currency')),
                ('effective_from', models.DateField(verbose_name='effective from date')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='effective to date')),
                ('salary_type', models.CharField(choices=[('MONTHLY', 'Monthly Base Salary'), ('DAILY', 'Daily Rate'), ('HOURLY', 'Hourly Rate')], default='MONTHLY', max_length=20, verbose_name='salary calculation type')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive / Historical')], default='ACTIVE', max_length=20, verbose_name='profile status')),
                ('notes', models.TextField(blank=True, verbose_name='notes / reason')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_salary_profiles', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_salary_profiles', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_profiles', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
            ],
            options={
                'verbose_name': 'salary profile',
                'verbose_name_plural': 'salary profiles',
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['code'], name='payroll_pay_code_15ddbf_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['status'], name='payroll_pay_status_c18070_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['start_date', 'end_date'], name='payroll_pay_start_d_46a73f_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrecord',
            index=models.Index(fields=['period', 'employee'], name='payroll_pay_period__accb35_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrecord',
            index=models.Index(fields=['status'], name='payroll_pay_status_8662b7_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrecord',
            index=models.Index(fields=['payment_status'], name='payroll_pay_payment_ff25e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollrecord',
            constraint=models.UniqueConstraint(fields=('period', 'employee'), name='unique_employee_payroll_per_period'),
        ),
        migrations.AddIndex(
            model_name='salaryhistory',
            index=models.Index(fields=['user', '-created_at'], name='payroll_sal_user_id_e529c0_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryprofile',
            index=models.Index(fields=['user', 'status'], name='payroll_sal_user_id_d3654c_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryprofile',
            index=models.Index(fields=['effective_from'], name='payroll_sal_effecti_3b6a27_idx'),
        ),
    ]
