# Generated by Django 5.1.15 on 2026-09-03 04:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpipayrollrule',
            name='effective_from',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='effective from'),
        ),
        migrations.AlterField(
            model_name='payrolltaxrule',
            name='effective_from',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='effective from date'),
        ),
    ]
