# Generated by Django 5.1.15 on 2026-09-03 06:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_kpipayrollrule_effective_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPermissionConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_view_payroll', models.BooleanField(default=True, verbose_name='can view payroll')),
                ('can_manage_salary', models.BooleanField(default=False, verbose_name='can manage employee salaries')),
                ('can_manage_compensation', models.BooleanField(default=False, verbose_name='can manage compensation components')),
                ('can_calculate_payroll', models.BooleanField(default=False, verbose_name='can calculate payroll')),
                ('can_create_adjustment', models.BooleanField(default=False, verbose_name='can create adjustments')),
                ('can_approve_payroll', models.BooleanField(default=False, verbose_name='can approve payroll')),
                ('can_mark_paid', models.BooleanField(default=False, verbose_name='can mark payroll as paid')),
                ('can_view_payroll_reports', models.BooleanField(default=False, verbose_name='can view payroll reports')),
                ('can_manage_tax_rules', models.BooleanField(default=False, verbose_name='can manage tax rules')),
                ('can_manage_kpi_payroll_rules', models.BooleanField(default=False, verbose_name='can manage KPI payroll rules')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_authority', to=settings.AUTH_USER_MODEL, verbose_name='authorized user')),
            ],
            options={
                'verbose_name': 'payroll authority configuration',
                'verbose_name_plural': 'payroll authority configurations',
            },
        ),
    ]
