# Generated by Django 6.1 on 2026-08-28 15:23

import django.db.models.deletion
import files.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0004_tasknote_visibility_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFolder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='folder name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task_folders', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='files.taskfolder', verbose_name='parent folder')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='tasks.task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'task folder',
                'verbose_name_plural': 'task folders',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=files.validators.task_file_upload_to, verbose_name='file')),
                ('original_filename', models.CharField(max_length=255, verbose_name='original filename')),
                ('stored_filename', models.CharField(blank=True, max_length=255, verbose_name='stored filename')),
                ('file_extension', models.CharField(db_index=True, max_length=20, verbose_name='extension')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='MIME content type')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='file size (bytes)')),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='SHA-256 Checksum')),
                ('category', models.CharField(choices=[('WORK_EVIDENCE', 'Work Evidence'), ('REQUIREMENTS', 'Requirements & Specs'), ('REPORT_ATTACHMENT', 'Report Attachment'), ('APPROVAL_DOCUMENT', 'Approval Document'), ('FINAL_SUBMISSION', 'Final Submission Document'), ('GENERAL', 'General Document')], db_index=True, default='WORK_EVIDENCE', max_length=30, verbose_name='category')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='tasks.taskassignment', verbose_name='assignment')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_task_files', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='tasks.tasksubmission', verbose_name='submission')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tasks.task', verbose_name='task')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_task_files', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='files.taskfolder', verbose_name='folder')),
            ],
            options={
                'verbose_name': 'task file',
                'verbose_name_plural': 'task files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='report title')),
                ('reporting_period', models.CharField(blank=True, max_length=150, verbose_name='reporting period / milestone')),
                ('summary', models.TextField(verbose_name='executive summary')),
                ('completed_work', models.TextField(verbose_name='completed work details')),
                ('results', models.TextField(verbose_name='key results & deliverables')),
                ('problems', models.TextField(blank=True, verbose_name='identified challenges & issues')),
                ('recommendations', models.TextField(blank=True, verbose_name='recommendations & next steps')),
                ('conclusion', models.TextField(blank=True, verbose_name='conclusion')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Review'), ('APPROVED', 'Approved by Leadership'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=30, verbose_name='status')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='tasks.taskassignment', verbose_name='assignment')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_task_reports', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='tasks.task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'task report',
                'verbose_name_plural': 'task reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='taskfolder',
            index=models.Index(fields=['task', 'is_active'], name='files_taskf_task_id_ddbdf5_idx'),
        ),
        migrations.AddIndex(
            model_name='taskfolder',
            index=models.Index(fields=['parent_folder'], name='files_taskf_parent__5aedcb_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskfolder',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('task', 'parent_folder', 'name'), name='unique_active_folder_per_parent'),
        ),
        migrations.AddIndex(
            model_name='taskfile',
            index=models.Index(fields=['task', 'is_active'], name='files_taskf_task_id_fc7206_idx'),
        ),
        migrations.AddIndex(
            model_name='taskfile',
            index=models.Index(fields=['assignment', 'is_active'], name='files_taskf_assignm_5b54b3_idx'),
        ),
        migrations.AddIndex(
            model_name='taskfile',
            index=models.Index(fields=['submission', 'is_active'], name='files_taskf_submiss_636e53_idx'),
        ),
        migrations.AddIndex(
            model_name='taskfile',
            index=models.Index(fields=['folder', 'is_active'], name='files_taskf_folder__e31882_idx'),
        ),
        migrations.AddIndex(
            model_name='taskfile',
            index=models.Index(fields=['uploaded_by', 'is_active'], name='files_taskf_uploade_88b82a_idx'),
        ),
        migrations.AddIndex(
            model_name='taskfile',
            index=models.Index(fields=['category', 'is_active'], name='files_taskf_categor_c35754_idx'),
        ),
        migrations.AddIndex(
            model_name='taskfile',
            index=models.Index(fields=['file_extension'], name='files_taskf_file_ex_a2a04d_idx'),
        ),
        migrations.AddIndex(
            model_name='taskreport',
            index=models.Index(fields=['task', 'status'], name='files_taskr_task_id_4c68eb_idx'),
        ),
        migrations.AddIndex(
            model_name='taskreport',
            index=models.Index(fields=['author', 'status'], name='files_taskr_author__208a68_idx'),
        ),
    ]
