# Generated by Django 6.1 on 2026-09-02 16:40

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        ('organization', '0002_department_head_position_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPICategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('order', models.IntegerField(default=1, verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'KPI category',
                'verbose_name_plural': 'KPI categories',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['code'], name='kpi_kpicate_code_cd396d_idx'), models.Index(fields=['is_active'], name='kpi_kpicate_is_acti_286b04_idx')],
            },
        ),
        migrations.CreateModel(
            name='KPIDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('measurement_type', models.CharField(choices=[('PERCENTAGE', 'Percentage (0-100%)'), ('NUMERIC', 'Numeric Value'), ('BOOLEAN', 'Yes / No'), ('COUNT', 'Count / Quantity'), ('RATING', 'Rating Score (1-5)')], default='PERCENTAGE', max_length=20, verbose_name='measurement type')),
                ('target_value', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=8, verbose_name='default target')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='default weight (%)')),
                ('min_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='min value')),
                ('max_value', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=8, verbose_name='max value')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('applicable_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicable_kpis', to='organization.department', verbose_name='applicable department')),
                ('applicable_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicable_kpis', to='hr.employeegrade', verbose_name='applicable grade')),
                ('applicable_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicable_kpis', to='organization.position', verbose_name='applicable position')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='definitions', to='kpi.kpicategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'KPI definition',
                'verbose_name_plural': 'KPI definitions',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KPIPeriod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('period_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='QUARTERLY', max_length=20, verbose_name='period type')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open / Active'), ('CLOSED', 'Closed / Finalized')], default='OPEN', max_length=20, verbose_name='status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_kpi_periods', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kpi_periods', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'KPI period',
                'verbose_name_plural': 'KPI periods',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='KPIAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='target value')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='weight (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_kpi_definitions', to=settings.AUTH_USER_MODEL, verbose_name='assigned by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_assignments', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='kpi.kpidefinition', verbose_name='KPI definition')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='kpi.kpiperiod', verbose_name='period')),
            ],
            options={
                'verbose_name': 'KPI assignment',
                'verbose_name_plural': 'KPI assignments',
                'ordering': ['user', 'kpi'],
            },
        ),
        migrations.CreateModel(
            name='KPIResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actual_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='actual value')),
                ('raw_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='raw score (0-100)')),
                ('weighted_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='weighted score')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Review'), ('REVIEWED', 'Reviewed by Manager'), ('APPROVED', 'Approved & Finalized')], default='DRAFT', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='evaluator notes / feedback')),
                ('evaluated_at', models.DateTimeField(blank=True, null=True, verbose_name='evaluated at')),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='kpi.kpiassignment', verbose_name='KPI assignment')),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_kpi_results', to=settings.AUTH_USER_MODEL, verbose_name='evaluated by')),
            ],
            options={
                'verbose_name': 'KPI result',
                'verbose_name_plural': 'KPI results',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='kpidefinition',
            index=models.Index(fields=['code'], name='kpi_kpidefi_code_c939ed_idx'),
        ),
        migrations.AddIndex(
            model_name='kpidefinition',
            index=models.Index(fields=['is_active'], name='kpi_kpidefi_is_acti_dd752e_idx'),
        ),
        migrations.AddIndex(
            model_name='kpiperiod',
            index=models.Index(fields=['code'], name='kpi_kpiperi_code_085258_idx'),
        ),
        migrations.AddIndex(
            model_name='kpiperiod',
            index=models.Index(fields=['status'], name='kpi_kpiperi_status_9bda12_idx'),
        ),
        migrations.AddIndex(
            model_name='kpiperiod',
            index=models.Index(fields=['is_active'], name='kpi_kpiperi_is_acti_24fc09_idx'),
        ),
        migrations.AddIndex(
            model_name='kpiassignment',
            index=models.Index(fields=['user', 'period'], name='kpi_kpiassi_user_id_54c046_idx'),
        ),
        migrations.AddIndex(
            model_name='kpiassignment',
            index=models.Index(fields=['period', 'is_active'], name='kpi_kpiassi_period__044060_idx'),
        ),
        migrations.AddConstraint(
            model_name='kpiassignment',
            constraint=models.UniqueConstraint(fields=('kpi', 'user', 'period'), name='unique_user_kpi_per_period'),
        ),
        migrations.AddIndex(
            model_name='kpiresult',
            index=models.Index(fields=['status'], name='kpi_kpiresu_status_4f3596_idx'),
        ),
    ]
