# Generated by Django 5.1.15 on 2026-09-14 04:56

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_hrpermissionconfig_can_approve_payroll_and_more'),
        ('kpi', '0001_initial'),
        ('organization', '0004_actingrectordelegation'),
        ('signatures', '0002_electronicsignature_signed_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPICorrectionRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_actual_value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='requested actual value')),
                ('reason', models.TextField(verbose_name='justification / correction reason')),
                ('evidence', models.TextField(blank=True, verbose_name='supporting evidence / documentation')),
                ('status', models.CharField(choices=[('REQUESTED', 'Correction Requested'), ('HR_REVIEW', 'Under HR Review'), ('PENDING_RECTOR', 'Pending Rector Decision'), ('APPROVED', 'Correction Approved'), ('REJECTED', 'Correction Rejected')], default='REQUESTED', max_length=25, verbose_name='status')),
                ('review_notes', models.TextField(blank=True, verbose_name='HR review notes')),
                ('rector_decision_reason', models.TextField(blank=True, verbose_name='rector decision reason')),
            ],
            options={
                'verbose_name': 'KPI correction request',
                'verbose_name_plural': 'KPI correction requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KPISnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_payload', models.JSONField(help_text='Deterministic JSON snapshot containing all employee scores and evidence.', verbose_name='canonical payload')),
                ('payload_hash', models.CharField(help_text='SHA-256 hash of the canonical payload.', max_length=64, verbose_name='payload hash')),
                ('total_employees', models.PositiveIntegerField(default=0, verbose_name='total evaluated employees')),
                ('average_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='university average score')),
            ],
            options={
                'verbose_name': 'KPI period snapshot',
                'verbose_name_plural': 'KPI period snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='kpiassignment',
            name='configured_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='configured weight (%)'),
        ),
        migrations.AddField(
            model_name='kpiassignment',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_kpi_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='designated evaluator'),
        ),
        migrations.AddField(
            model_name='kpiassignment',
            name='normalized_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='normalized weight (%)'),
        ),
        migrations.AddField(
            model_name='kpiassignment',
            name='source_type',
            field=models.CharField(blank=True, max_length=35, verbose_name='source type'),
        ),
        migrations.AddField(
            model_name='kpicategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kpi_categories', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='kpidefinition',
            name='configured_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='configured weight (%)'),
        ),
        migrations.AddField(
            model_name='kpidefinition',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kpi_definitions', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='kpidefinition',
            name='direction',
            field=models.CharField(choices=[('HIGHER_IS_BETTER', 'Higher is Better'), ('LOWER_IS_BETTER', 'Lower is Better'), ('TARGET_IS_BEST', 'Target is Best')], default='HIGHER_IS_BETTER', max_length=25, verbose_name='direction'),
        ),
        migrations.AddField(
            model_name='kpidefinition',
            name='no_data_policy',
            field=models.CharField(choices=[('EXCLUDED', 'Exclude from Score Calculation (No Penalty)'), ('ZERO', 'Treat as Zero Score (0%)'), ('MANUAL_REVIEW', 'Flag for Manual Review')], default='EXCLUDED', max_length=20, verbose_name='no data policy'),
        ),
        migrations.AddField(
            model_name='kpidefinition',
            name='source_type',
            field=models.CharField(choices=[('TASK_SYSTEM', 'Task Management Subsystem (Automatic)'), ('WORKFLOW_SYSTEM', 'Workflow Subsystem (Automatic)'), ('MANUAL_MANAGER_EVALUATION', 'Manual Manager Evaluation'), ('HR_EVALUATION', 'HR Department Evaluation'), ('STRATEGIC_TARGET', 'Strategic Target / Executive Metric'), ('OTHER', 'Other Source')], default='MANUAL_MANAGER_EVALUATION', max_length=35, verbose_name='source type'),
        ),
        migrations.AddField(
            model_name='kpiperiod',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='rejection reason'),
        ),
        migrations.AddField(
            model_name='kpiperiod',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='signed at'),
        ),
        migrations.AddField(
            model_name='kpiperiod',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_kpi_periods', to=settings.AUTH_USER_MODEL, verbose_name='signed by'),
        ),
        migrations.AddField(
            model_name='kpiresult',
            name='calculation_evidence',
            field=models.JSONField(blank=True, default=dict, verbose_name='calculation evidence & task breakdown'),
        ),
        migrations.AddField(
            model_name='kpiresult',
            name='configured_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='configured weight (%)'),
        ),
        migrations.AddField(
            model_name='kpiresult',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='locked against modification'),
        ),
        migrations.AddField(
            model_name='kpiresult',
            name='normalized_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='normalized weight (%)'),
        ),
        migrations.AddField(
            model_name='kpiresult',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='result version'),
        ),
        migrations.AlterField(
            model_name='kpiassignment',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='weight (%)'),
        ),
        migrations.AlterField(
            model_name='kpidefinition',
            name='measurement_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage (0-100%)'), ('NUMERIC', 'Numeric Value'), ('BOOLEAN', 'Yes / No'), ('COUNT', 'Count / Quantity'), ('RATING', 'Rating Score (1-5)'), ('TASK_COMPLETION', 'Task Completion Rate'), ('DEADLINE_COMPLIANCE', 'Deadline Compliance Rate'), ('QUALITY', 'Work & Deliverable Quality'), ('DURATION', 'Turnaround Duration'), ('CUSTOM', 'Custom Indicator')], default='PERCENTAGE', max_length=30, verbose_name='measurement type'),
        ),
        migrations.AlterField(
            model_name='kpiperiod',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open / Active'), ('CALCULATING', 'Calculating'), ('UNDER_REVIEW', 'Under Review'), ('HR_VERIFIED', 'HR Verified'), ('PENDING_RECTOR_APPROVAL', 'Pending Rector Approval'), ('RECTOR_APPROVED', 'Rector Approved'), ('RECTOR_SIGNED', 'Rector Signed / Finalized'), ('CLOSED', 'Closed / Archived')], default='OPEN', max_length=30, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='kpiresult',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Review'), ('REVIEWED', 'Reviewed by Manager'), ('HR_VERIFIED', 'HR Verified'), ('APPROVED', 'Approved & Finalized'), ('LOCKED', 'Signed & Locked')], default='DRAFT', max_length=25, verbose_name='status'),
        ),
        migrations.AddIndex(
            model_name='kpidefinition',
            index=models.Index(fields=['source_type'], name='kpi_kpidefi_source__2d4bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='kpiresult',
            index=models.Index(fields=['is_locked'], name='kpi_kpiresu_is_lock_5e448e_idx'),
        ),
        migrations.AddField(
            model_name='kpicorrectionrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kpi_corrections_requested', to=settings.AUTH_USER_MODEL, verbose_name='requester'),
        ),
        migrations.AddField(
            model_name='kpicorrectionrequest',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_requests', to='kpi.kpiresult', verbose_name='original KPI result'),
        ),
        migrations.AddField(
            model_name='kpicorrectionrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_corrections_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by'),
        ),
        migrations.AddField(
            model_name='kpisnapshot',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='kpi.kpiperiod', verbose_name='KPI period'),
        ),
        migrations.AddField(
            model_name='kpisnapshot',
            name='signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_snapshots', to='signatures.electronicsignature', verbose_name='electronic signature'),
        ),
    ]
