# Generated by Django 6.1 on 2026-09-04 07:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0003_position_can_supervise'),
        ('tasks', '0004_tasknote_visibility_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='escalation policy name')),
                ('trigger_type', models.CharField(choices=[('DEADLINE_APPROACHING', 'Deadline Approaching'), ('DEADLINE_PASSED', 'Deadline Passed / Overdue'), ('APPROVAL_STAGE_1_OVERDUE', 'Stage 1 Approval Overdue'), ('APPROVAL_STAGE_2_OVERDUE', 'Stage 2 Final Approval Overdue')], max_length=40, verbose_name='trigger type')),
                ('hours_threshold', models.IntegerField(default=24, help_text='Hours relative to deadline or submission (e.g., -24 for 24h prior, 24 for 24h overdue, 48 for 48h overdue).', verbose_name='hours threshold')),
                ('escalate_to_role', models.CharField(choices=[('SUPERVISOR', 'Direct Supervisor / Lead'), ('DEPARTMENT_HEAD', 'Department Head'), ('VICE_RECTOR', 'Supervising Vice Rector'), ('RECTOR', 'University Rector'), ('SUPERADMIN', 'Technical Superadmin')], max_length=40, verbose_name='escalate to role')),
                ('send_email', models.BooleanField(default=True, verbose_name='send email notification')),
                ('send_telegram', models.BooleanField(default=False, verbose_name='send telegram notification')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'escalation policy',
                'verbose_name_plural': 'escalation policies',
                'ordering': ['trigger_type', 'hours_threshold'],
            },
        ),
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='policy name')),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=20, unique=True, verbose_name='priority level')),
                ('first_response_hours', models.PositiveIntegerField(default=24, help_text='Maximum hours allowed before task assignment is accepted or work starts.', verbose_name='first response deadline (hours)')),
                ('resolution_hours', models.PositiveIntegerField(default=72, help_text='Maximum hours allowed before task completion and final approval.', verbose_name='resolution deadline (hours)')),
                ('warning_threshold_percent', models.PositiveIntegerField(default=80, help_text='Percentage of resolution time elapsed before SLA warning is triggered.', verbose_name='warning threshold (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'SLA policy',
                'verbose_name_plural': 'SLA policies',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='rule name')),
                ('description', models.TextField(blank=True, verbose_name='rule description')),
                ('trigger_event', models.CharField(choices=[('TASK_CREATED', 'Task Created'), ('DEADLINE_APPROACHING', 'Deadline Approaching (<=24h)'), ('TASK_OVERDUE', 'Task Overdue'), ('SUBMISSION_CREATED', 'Deliverable Submitted'), ('FIRST_APPROVAL_OVERDUE', 'First Approval Pending > 24h'), ('TASK_COMPLETED', 'Task Completed (Final Approved)'), ('SIGNATURE_CREATED', 'Task Cryptographically Signed')], max_length=40, verbose_name='trigger event')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='JSON conditions, e.g. {"priority": "HIGH", "department_code": "IT"}', verbose_name='rule conditions')),
                ('action_type', models.CharField(choices=[('SEND_NOTIFICATION', 'Send Push & System Notification'), ('ESCALATE_SUPERVISOR', 'Escalate to Department Head'), ('ESCALATE_VICE_RECTOR', 'Escalate to Supervising Vice Rector'), ('ESCALATE_RECTOR', 'Escalate to Rector'), ('SET_PRIORITY', 'Increase Task Priority'), ('AUTO_ASSIGN', 'Auto-Assign Responsible Users')], max_length=40, verbose_name='action type')),
                ('action_config', models.JSONField(blank=True, default=dict, help_text='Action payload, e.g. {"message": "High priority task notification", "target_priority": "CRITICAL"}', verbose_name='action configuration')),
                ('priority_order', models.PositiveIntegerField(default=10, verbose_name='execution priority order')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_automation_rules', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'automation rule',
                'verbose_name_plural': 'automation rules',
                'ordering': ['priority_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecurringTaskRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='recurring task title')),
                ('description', models.TextField(blank=True, verbose_name='task description')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20, verbose_name='priority')),
                ('recurrence_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom Interval')], default='WEEKLY', max_length=20, verbose_name='recurrence interval')),
                ('day_of_week', models.IntegerField(blank=True, help_text='0=Monday, 6=Sunday (for Weekly recurrence)', null=True, verbose_name='day of week')),
                ('day_of_month', models.IntegerField(blank=True, help_text='1-31 (for Monthly/Quarterly recurrence)', null=True, verbose_name='day of month')),
                ('time_of_day', models.TimeField(default='09:00:00', verbose_name='generation time of day')),
                ('deadline_offset_days', models.PositiveIntegerField(default=7, help_text='Number of days from generation date until the task deadline.', verbose_name='deadline offset (days)')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='last executed at')),
                ('next_run_at', models.DateTimeField(blank=True, null=True, verbose_name='next scheduled run')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('assignees', models.ManyToManyField(blank=True, related_name='recurring_task_assignments', to=settings.AUTH_USER_MODEL, verbose_name='default assignees')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recurring_task_rules', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('responsible_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_task_rules', to='organization.department', verbose_name='responsible department')),
                ('task_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_task_rules', to='tasks.tasktype', verbose_name='task type')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_task_rules', to='tasks.tasktemplate', verbose_name='task template')),
            ],
            options={
                'verbose_name': 'recurring task rule',
                'verbose_name_plural': 'recurring task rules',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='AutomationExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_event', models.CharField(max_length=40, verbose_name='trigger event')),
                ('target_repr', models.CharField(max_length=255, verbose_name='target entity')),
                ('target_id', models.CharField(blank=True, max_length=64, verbose_name='target ID')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped / No-Op')], default='SUCCESS', max_length=20, verbose_name='execution status')),
                ('result_summary', models.TextField(verbose_name='result summary')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='executed at')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='automation.automationrule', verbose_name='triggered rule')),
            ],
            options={
                'verbose_name': 'automation execution log',
                'verbose_name_plural': 'automation execution logs',
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['-executed_at'], name='automation__execute_eb8d49_idx'), models.Index(fields=['status'], name='automation__status_6b6b3b_idx'), models.Index(fields=['trigger_event'], name='automation__trigger_12bfed_idx')],
            },
        ),
    ]
