# Generated by Django 6.1 on 2026-09-04 07:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0003_position_can_supervise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='category name')),
                ('code', models.CharField(choices=[('ACADEMIC', 'Academic & Curriculum'), ('ADMINISTRATIVE', 'Administrative & Governance'), ('HR_LEAVE', 'Human Resources & Leave Requests'), ('FINANCIAL', 'Financial, Grants & Procurement'), ('FACILITIES', 'Facilities, Logistics & Campus'), ('IT_SERVICES', 'IT & Digital Infrastructure')], max_length=40, unique=True, verbose_name='category code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon_class', models.CharField(default='bi-folder2-open', max_length=50, verbose_name='bootstrap icon class')),
                ('display_order', models.PositiveIntegerField(default=10, verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'request category',
                'verbose_name_plural': 'request categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180, verbose_name='request type name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='request type code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('requires_dept_head_approval', models.BooleanField(default=True, verbose_name='requires Department Head approval')),
                ('requires_dean_or_vr_approval', models.BooleanField(default=True, verbose_name='requires Dean / Vice Rector approval')),
                ('requires_hr_approval', models.BooleanField(default=False, verbose_name='requires HR Manager approval')),
                ('requires_finance_approval', models.BooleanField(default=False, verbose_name='requires Finance approval')),
                ('requires_rector_approval', models.BooleanField(default=False, verbose_name='requires Rector final approval')),
                ('sla_resolution_hours', models.PositiveIntegerField(default=72, verbose_name='standard resolution SLA (hours)')),
                ('form_schema', models.JSONField(blank=True, default=list, help_text='JSON schema defining required custom inputs (e.g. leave dates, equipment specs, budgets).', verbose_name='dynamic form fields schema')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_types', to='operations.requestcategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'request type',
                'verbose_name_plural': 'request types',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UniversityDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_number', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='official document reference number')),
                ('title', models.CharField(max_length=300, verbose_name='document title')),
                ('document_type', models.CharField(choices=[('ORDER_RECTOR', 'Rector Order / Buyruq'), ('REGULATION', 'University Regulation / Nizom'), ('DECREE_MINISTRY', 'Ministry Decree / Qaror'), ('PROTOCOL_SENATE', 'Senate Protocol / Bayonnoma'), ('MEMORANDUM', 'Internal Memorandum / Xizmat xati')], max_length=40, verbose_name='document type')),
                ('description', models.TextField(blank=True, verbose_name='summary / description')),
                ('file', models.FileField(upload_to='documents/official/', verbose_name='official document file (PDF/Doc)')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='document version')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'Under Review'), ('SIGNED_ENACTED', 'Signed & In Effect'), ('ARCHIVED', 'Archived / Superseded')], default='SIGNED_ENACTED', max_length=30, verbose_name='status')),
                ('effective_date', models.DateField(default=django.utils.timezone.now, verbose_name='effective date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='expiry date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_university_documents', to=settings.AUTH_USER_MODEL, verbose_name='created / registered by')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_documents', to='organization.department', verbose_name='issuing department')),
            ],
            options={
                'verbose_name': 'university document',
                'verbose_name_plural': 'university documents',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UniversityRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(blank=True, db_index=True, max_length=30, unique=True, verbose_name='request tracking number')),
                ('subject', models.CharField(max_length=255, verbose_name='request subject / title')),
                ('details_payload', models.JSONField(blank=True, default=dict, verbose_name='request form data payload')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted / In Review'), ('IN_REVIEW', 'Under Multi-Tier Review'), ('APPROVED', 'Fully Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled by Requester'), ('COMPLETED', 'Fulfilled & Completed')], db_index=True, default='SUBMITTED', max_length=30, verbose_name='status')),
                ('current_step_number', models.PositiveIntegerField(default=1, verbose_name='current approval step number')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='marked as urgent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved / completed at')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_requests', to='organization.department', verbose_name='originating department')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='operations.requesttype', verbose_name='request type')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_requests', to=settings.AUTH_USER_MODEL, verbose_name='requester')),
            ],
            options={
                'verbose_name': 'university request',
                'verbose_name_plural': 'university requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestApprovalStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.PositiveIntegerField(default=1, verbose_name='step order number')),
                ('approver_role', models.CharField(choices=[('DEPARTMENT_HEAD', 'Department Head'), ('VICE_RECTOR', 'Supervising Vice Rector / Dean'), ('HR_MANAGER', 'HR Department'), ('FINANCE_DIRECTOR', 'Finance & Accounting'), ('RECTOR', 'University Rector')], max_length=40, verbose_name='approver role')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Decision'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20, verbose_name='decision status')),
                ('comments', models.TextField(blank=True, verbose_name='approver comments / justification')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decided at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('assigned_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_request_approvals', to=settings.AUTH_USER_MODEL, verbose_name='assigned specific approver')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_request_steps', to=settings.AUTH_USER_MODEL, verbose_name='decided by user')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='operations.universityrequest', verbose_name='university request')),
            ],
            options={
                'verbose_name': 'request approval step',
                'verbose_name_plural': 'request approval steps',
                'ordering': ['request', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(verbose_name='version number')),
                ('file', models.FileField(upload_to='documents/versions/', verbose_name='version file')),
                ('changelog', models.TextField(blank=True, verbose_name='change summary')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_document_versions', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='operations.universitydocument', verbose_name='document')),
            ],
            options={
                'verbose_name': 'document version',
                'verbose_name_plural': 'document versions',
                'ordering': ['-version_number'],
                'constraints': [models.UniqueConstraint(fields=('document', 'version_number'), name='unique_document_version_number')],
            },
        ),
        migrations.AddIndex(
            model_name='universityrequest',
            index=models.Index(fields=['requester', 'status'], name='operations__request_d4a801_idx'),
        ),
        migrations.AddIndex(
            model_name='universityrequest',
            index=models.Index(fields=['status', '-created_at'], name='operations__status_fcb907_idx'),
        ),
        migrations.AddConstraint(
            model_name='requestapprovalstep',
            constraint=models.UniqueConstraint(fields=('request', 'step_number'), name='unique_request_step_number'),
        ),
    ]
