# Generated by Django 5.1.15 on 2026-09-04 04:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0004_tasknote_visibility_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signature_type', models.CharField(choices=[('RECTOR_SIGNATURE', 'Rector Electronic Signature'), ('VICE_RECTOR_SIGNATURE', 'Vice Rector Electronic Signature'), ('SUPERADMIN_SIGNATURE', 'Superadmin Administrative Signature'), ('OTHER_AUTHORIZED_SIGNATURE', 'Other Authorized Signature')], db_index=True, default='RECTOR_SIGNATURE', max_length=40, verbose_name='signature type')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SIGNED', 'Signed / Valid'), ('REVOKED', 'Revoked'), ('INVALID', 'Invalid')], db_index=True, default='SIGNED', max_length=20, verbose_name='status')),
                ('signed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='signed at')),
                ('verification_id', models.CharField(db_index=True, help_text='Cryptographically secure, non-guessable public identifier (e.g., SIG-2026-XXXXXXXX).', max_length=64, unique=True, verbose_name='verification ID')),
                ('verification_token', models.CharField(db_index=True, help_text='Secure opaque token for public URL lookup.', max_length=128, unique=True, verbose_name='verification token')),
                ('snapshot_hash', models.CharField(db_index=True, help_text='Cryptographic SHA-256 hash of the complete canonical snapshot.', max_length=64, verbose_name='snapshot SHA-256 hash')),
                ('payload_hash', models.CharField(db_index=True, help_text='SHA-256 checksum of the canonical task payload that was signed.', max_length=64, verbose_name='payload SHA-256 hash')),
                ('signature_value', models.TextField(help_text='Base64-encoded asymmetric digital signature (Ed25519).', verbose_name='digital signature value')),
                ('algorithm', models.CharField(default='Ed25519', max_length=50, verbose_name='cryptographic algorithm')),
                ('key_version', models.CharField(default='v1', max_length=32, verbose_name='key version')),
                ('public_key_reference', models.TextField(blank=True, help_text='PEM or Base64 encoding of the public key for historical verification.', verbose_name='public key reference / PEM')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
                ('revocation_reason', models.TextField(blank=True, verbose_name='revocation reason')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_signatures', to=settings.AUTH_USER_MODEL, verbose_name='revoked by')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electronic_signatures', to=settings.AUTH_USER_MODEL, verbose_name='signer')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='tasks.task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'electronic signature',
                'verbose_name_plural': 'electronic signatures',
                'ordering': ['-signed_at'],
            },
        ),
        migrations.CreateModel(
            name='SignatureSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_payload', models.JSONField(help_text='Deterministic canonical JSON representation of the signed task.', verbose_name='canonical payload')),
                ('payload_hash', models.CharField(help_text='SHA-256 checksum matching the signature record.', max_length=64, verbose_name='payload hash')),
                ('schema_version', models.PositiveIntegerField(default=1, verbose_name='schema version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('signature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='signatures.electronicsignature', verbose_name='electronic signature')),
            ],
            options={
                'verbose_name': 'signature snapshot',
                'verbose_name_plural': 'signature snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignatureVerificationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_id', models.CharField(db_index=True, max_length=64, verbose_name='verification ID requested')),
                ('is_valid', models.BooleanField(default=False, verbose_name='verification passed')),
                ('failure_reason', models.CharField(blank=True, max_length=255, verbose_name='failure reason')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('verified_at', models.DateTimeField(auto_now_add=True, verbose_name='verified at')),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_events', to='signatures.electronicsignature', verbose_name='electronic signature')),
            ],
            options={
                'verbose_name': 'signature verification event',
                'verbose_name_plural': 'signature verification events',
                'ordering': ['-verified_at'],
            },
        ),
        migrations.AddIndex(
            model_name='electronicsignature',
            index=models.Index(fields=['task', 'status'], name='signatures__task_id_679bd7_idx'),
        ),
        migrations.AddIndex(
            model_name='electronicsignature',
            index=models.Index(fields=['signer', 'status'], name='signatures__signer__692e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='electronicsignature',
            index=models.Index(fields=['signed_at'], name='signatures__signed__45bbc3_idx'),
        ),
        migrations.AddIndex(
            model_name='electronicsignature',
            index=models.Index(fields=['verification_id'], name='signatures__verific_7087b6_idx'),
        ),
        migrations.AddIndex(
            model_name='electronicsignature',
            index=models.Index(fields=['verification_token'], name='signatures__verific_2ba098_idx'),
        ),
        migrations.AddIndex(
            model_name='signatureverificationevent',
            index=models.Index(fields=['verification_id', 'verified_at'], name='signatures__verific_f93e17_idx'),
        ),
        migrations.AddIndex(
            model_name='signatureverificationevent',
            index=models.Index(fields=['is_valid', 'verified_at'], name='signatures__is_vali_986fc7_idx'),
        ),
    ]
