# Generated by Django 6.1 on 2026-09-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicsignature',
            name='signed_pdf',
            field=models.FileField(blank=True, help_text='Officially generated PDF document with electronic signature seal and QR code.', null=True, upload_to='signatures/pdf/%Y/%m/', verbose_name='signed PDF document'),
        ),
    ]
