# Generated by Django 5.1.15 on 2026-09-14 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0002_kpicorrectionrequest_kpisnapshot_and_more'),
        ('signatures', '0002_electronicsignature_signed_pdf'),
        ('tasks', '0006_alter_taskhistory_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicsignature',
            name='kpi_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='kpi.kpiperiod', verbose_name='KPI period'),
        ),
        migrations.AlterField(
            model_name='electronicsignature',
            name='signature_type',
            field=models.CharField(choices=[('RECTOR_SIGNATURE', 'Rector Electronic Signature'), ('VICE_RECTOR_SIGNATURE', 'Vice Rector Electronic Signature'), ('SUPERADMIN_SIGNATURE', 'Superadmin Administrative Signature'), ('KPI_PERIOD_SIGNATURE', 'Rector KPI Period Final Signature'), ('OTHER_AUTHORIZED_SIGNATURE', 'Other Authorized Signature')], db_index=True, default='RECTOR_SIGNATURE', max_length=40, verbose_name='signature type'),
        ),
        migrations.AlterField(
            model_name='electronicsignature',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='tasks.task', verbose_name='task'),
        ),
    ]
