from django.urls import path

from payroll.views import (
    CompensationComponentCreateView,
    CompensationComponentListView,
    EmployeeCompensationDetailView,
    EmployeeCompensationListView,
    EmployeeMyPayslipsView,
    EmployeeMySalaryView,
    EmployeePayslipDetailView,
    KPIPayrollRuleCreateView,
    KPIPayrollRuleListView,
    PayrollAdjustmentCreateView,
    PayrollCalculatePeriodView,
    PayrollCalculateSingleView,
    PayrollDashboardView,
    PayrollPeriodApproveAllView,
    PayrollPeriodCloseView,
    PayrollPeriodCreateView,
    PayrollPeriodDetailView,
    PayrollPeriodListView,
    PayrollRecordApproveView,
    PayrollRecordDetailView,
    PayrollRecordListView,
    PayrollRecordMarkPaidView,
    PayrollReportsSummaryView,
    PayrollTaxRuleCreateView,
    PayrollTaxRuleListView,
    PayslipExportPDFView,
    PeriodExportExcelView,
    SalaryProfileCreateView,
)

app_name = 'payroll'

urlpatterns = [
    path('', PayrollDashboardView.as_view(), name='dashboard'),
    path('employees/', EmployeeCompensationListView.as_view(), name='employee_list'),
    path('employees/<uuid:pk>/', EmployeeCompensationDetailView.as_view(), name='employee_detail'),
    path('employees/<uuid:user_id>/salary/create/', SalaryProfileCreateView.as_view(), name='salary_create'),
    path('periods/', PayrollPeriodListView.as_view(), name='period_list'),
    path('periods/create/', PayrollPeriodCreateView.as_view(), name='period_create'),
    path('periods/<uuid:pk>/', PayrollPeriodDetailView.as_view(), name='period_detail'),
    path('periods/<uuid:pk>/calculate/', PayrollCalculatePeriodView.as_view(), name='period_calculate'),
    path('periods/<uuid:pk>/approve-all/', PayrollPeriodApproveAllView.as_view(), name='period_approve_all'),
    path('periods/<uuid:pk>/close/', PayrollPeriodCloseView.as_view(), name='period_close'),
    path('periods/<uuid:pk>/export/excel/', PeriodExportExcelView.as_view(), name='period_export_excel'),
    path('records/', PayrollRecordListView.as_view(), name='record_list'),
    path('records/<uuid:pk>/', PayrollRecordDetailView.as_view(), name='record_detail'),
    path('records/<uuid:pk>/approve/', PayrollRecordApproveView.as_view(), name='record_approve'),
    path('records/<uuid:pk>/mark-paid/', PayrollRecordMarkPaidView.as_view(), name='record_mark_paid'),
    path('records/<uuid:pk>/pdf/', PayslipExportPDFView.as_view(), name='record_pdf'),
    path('calculate/single/<uuid:user_id>/<uuid:period_id>/', PayrollCalculateSingleView.as_view(), name='calculate_single'),
    path('adjustments/create/', PayrollAdjustmentCreateView.as_view(), name='adjustment_create'),
    path('my/payslips/', EmployeeMyPayslipsView.as_view(), name='my_payslips'),
    path('my/payslips/<uuid:pk>/', EmployeePayslipDetailView.as_view(), name='my_payslip_detail'),
    path('my/salary/', EmployeeMySalaryView.as_view(), name='my_salary'),
    path('components/', CompensationComponentListView.as_view(), name='component_list'),
    path('components/create/', CompensationComponentCreateView.as_view(), name='component_create'),
    path('tax-rules/', PayrollTaxRuleListView.as_view(), name='tax_rule_list'),
    path('tax-rules/create/', PayrollTaxRuleCreateView.as_view(), name='tax_rule_create'),
    path('kpi-rules/', KPIPayrollRuleListView.as_view(), name='kpi_rule_list'),
    path('kpi-rules/create/', KPIPayrollRuleCreateView.as_view(), name='kpi_rule_create'),
    path('reports/', PayrollReportsSummaryView.as_view(), name='reports_summary'),
]
